server:
  port: 8002


#应用名称
spring:
  application:
    name: zcloud-data

  #服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 8.134.147.121:8848
        username: nacos
        password: WcW191002

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

