server:
  port: 8003

#-----------------------------------------------
#应用名称
spring:
  application:
    name: zcloud-link

  #服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 8.134.147.121:8848
        username: nacos
        password: WcW191002

#-----------------------------------------------
  #  数据库配置 配置ShardingSphere数据源
  shardingsphere:
    datasource:
      # 数据源名称
      names: ds0, ds1, dsa
      # 数据源ds0配置
      ds0:
        # 连接超时时间（毫秒）
        connectionTimeoutMilliseconds: 30000
        # 驱动类名
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 空闲超时时间（毫秒）
        idleTimeoutMilliseconds: 60000
        # JDBC连接URL
        jdbc-url: jdbc:mysql://8.134.147.121:3306/zcloud_link_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        # 维护间隔时间（毫秒）
        maintenanceIntervalMilliseconds: 30000
        # 连接最大生命周期（毫秒）
        maxLifetimeMilliseconds: 1800000
        # 连接池最大大小
        maxPoolSize: 50
        # 连接池最小大小
        minPoolSize: 50
        # 数据库用户名
        username: root
        # 数据库密码
        password: WcW191002
        # 数据源类型
        type: com.zaxxer.hikari.HikariDataSource
      # 数据源ds1配置
      ds1:
        # 连接超时时间（毫秒）
        connectionTimeoutMilliseconds: 30000
        # 驱动类名
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 空闲超时时间（毫秒）
        idleTimeoutMilliseconds: 60000
        # JDBC连接URL
        jdbc-url: jdbc:mysql://8.134.147.121:3306/zcloud_link_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        # 维护间隔时间（毫秒）
        maintenanceIntervalMilliseconds: 30000
        # 连接最大生命周期（毫秒）
        maxLifetimeMilliseconds: 1800000
        # 连接池最大大小
        maxPoolSize: 50
        # 连接池最小大小
        minPoolSize: 50
        # 数据库用户名
        username: root
        # 数据库密码
        password: WcW191002
        # 数据源类型
        type: com.zaxxer.hikari.HikariDataSource
      # 数据源dsa配置
      dsa:
        # 连接超时时间（毫秒）
        connectionTimeoutMilliseconds: 30000
        # 驱动类名
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 空闲超时时间（毫秒）
        idleTimeoutMilliseconds: 60000
        # JDBC连接URL
        jdbc-url: jdbc:mysql://8.134.147.121:3306/zcloud_link_a?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        # 维护间隔时间（毫秒）
        maintenanceIntervalMilliseconds: 30000
        # 连接最大生命周期（毫秒）
        maxLifetimeMilliseconds: 1800000
        # 连接池最大大小
        maxPoolSize: 50
        # 连接池最小大小
        minPoolSize: 50
        # 数据库用户名
        username: root
        # 数据库密码
        password: WcW191002
        # 数据源类型
        type: com.zaxxer.hikari.HikariDataSource
    props:
      # 打印执行的数据库以及语句
      sql:
        show: true
    # 分库分表配置具象配置
    sharding:
      # 不分库分表的默认数据源（当前是domain表ds0库）
      default-data-source-name: ds0
      default-key-generator:
        column: id
        props:
          worker:
            id: ${workId}
        type: SNOWFLAKE
      # 分库分表
      tables:
        # link_group表分库（2个库 1库1表）
        link_group:
          # 主键生成策略
          key-generator:
            column: id
            props:
              worker:
                id: ${workId}
            type: SNOWFLAKE
          # link_group表分库策略
          database-strategy:
            inline:
              sharding-column: account_no
              algorithm-expression: ds$->{account_no % 2}
        # short_link表分库且分表（3个库 1库2表）
        short_link:
          # 主键生成策略
          key-generator:
            column: id
            props:
              worker:
                id: ${workId}
            type: SNOWFLAKE
          # 指定数据节点
          actual-data-nodes: ds0.short_link,ds1.short_link,dsa.short_link
          # 分库策略
          database-strategy:
            standard:
              sharding-column: code
              precise-algorithm-class-name: com.zskj.link.strategy.sharding.CustomDBPreciseShardingAlgorithm
          # 分表策略
          table-strategy:
            standard:
              sharding-column: code
              precise-algorithm-class-name: com.zskj.link.strategy.sharding.CustomTablePreciseShardingAlgorithm

#-----------------------------------------------

